### PR TITLE
Standby Attitude Indicator improvements

### PR DESCRIPTION
**Pull request by MCCVeen**
Airplane Symbol color changed from Orange to Yellow so it matches the correct model of the Standby Attitude Indicator

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
This has been sitting here for a while. How about I try to do this again and create a new pull request. So you just changed the standby indicator from orange to yellow?

**Comment by crazytimtimtim** [comment]
Do you think you can give me a hint as to where the texture change it? I just can't find it!

**Comment by Matt726-S** [comment]
this doesn’t change anything and it just says that there’s a deleted file, can we close this pull request

**Comment by crazytimtimtim** [comment]
> 
> 
> this doesn’t change anything and it just says that there’s a deleted file, can we close this pull request

what... No.
He just deleted the file because it had a conflict, but that didn't fix it. Look at the first commit 27f1335 .

**Pull request closed without merging**
