### PR TITLE
Fix LEGS page when airborne.

### PR DESCRIPTION
**Pull request by crazytimtimtim**
Partial fix for #296, possible fix for #276
Some indentation was also changed but has no effect on the code's operation.

Thanks to Harrrvey on Discord.

### CODE REVIEW

**Comment by mSparks43** [comment]
This removes the ability to go direct to waypoint while in the air and doesn't replace this functionality anywhere else.

**Comment by crazytimtimtim** [comment]
> This removes the ability to go direct to waypoint while in the air and doesn't replace this functionality anywhere else.

Can't you just type the name and enter it via LSK L1 on the route page?

**Comment by mSparks43** [comment]
> > This removes the ability to go direct to waypoint while in the air and doesn't replace this functionality anywhere else.
> 
> Can't you just type the name and enter it via LSK L1 on the route page?

Legs generally gives "INVALID ENTRY" when trying to modify an active flight plan, the "on ground" check switches to the default intercept course direct functionality when airborne (because there is no INTC_DIR button)

**Comment by crazytimtimtim** [comment]
> This removes the ability to go direct to waypoint while in the air and doesn't replace this functionality anywhere else.
Ok. You should still be able to access the page if you click the LEGS button while already on the LEGS page.

**Comment by mSparks43** [comment]
but you can already access the legs page in the air, its rte2

**Comment by crazytimtimtim** [comment]
Fixed.

**Comment by crazytimtimtim** [comment]
I can close this if you'd like. All it really does is allows us to use the LEGS page in flight and "direct to" on the ground if we really want to. The legs button will still default to LEGS on ground and "direct to" in air.

Should I close?

**Pull request closed without merging**
