### PR TITLE
Partial fix for #490

### PR DESCRIPTION
**Pull request by crazytimtimtim**
Untested, will leave as a draft for now.

### CODE REVIEW

**Comment by oMrSmith** [comment]
You want me to test it? If so: Could you give me a tip how to do it
before the edit has been pulled?

**Comment by crazytimtimtim** [comment]
> You want me to test it?

That would be great, thanks. To test, head over to the [patch-7 branch on my fork](https://github.com/crazytimtimtim/747-400/tree/patch-7) and download it. It should cause the ref gate and ref airport lines to blank once you take off.

**Comment by crazytimtimtim** [comment]
@oMrSmith Yes please, read above!

**Comment by oMrSmith** [comment]
Test with engines started: Entering the REF airport does not fill out the field.
Field will remain: _ _ _ _

**Comment by crazytimtimtim** [comment]
Ok, I'll take a look.

**Comment by crazytimtimtim** [comment]
I'll fix this when I can. Right now my fork and local files are both a mess, with random incomplete fixes I need to get done😆. Once mSparks merges my other pull request I think things will get clearer.

**Comment by crazytimtimtim** [comment]
Will close for no. I've got another pull request to get open, then I'll get to this one.

**Pull request closed without merging**
