### PR TITLE
Rename of All Liveries to Give Credit

### PR DESCRIPTION
**Pull request by THEONEANDONLYPLANE**

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
Speaking of liveries, I know some of them have their own cockpit window textures. Do you think you can copy those into the main objects folder so all the liveries have it?

**Comment by mSparks43** [comment]
does the global super tanker loading still work after the rename?

**Comment by Matt726-S** [comment]
for the 4X-ICB, i made it. also the airline is not challenge accepted, its “CAL cargo airlines”: https://en.wikipedia.org/wiki/CAL_Cargo_Air_Lines
their icao is ICL.
i made this livery because these two youtubers fly for the airline on this plane https://youtube.com/c/CaptainBoeing
https://youtube.com/c/747Pilot

**Comment by Matt726-S** [comment]
for the 4X-ICB, i made it. also the airline is not challenge accepted, its “CAL cargo airlines”: https://en.wikipedia.org/wiki/CAL_Cargo_Air_Lines
their icao is ICL.
i made this livery because these two youtubers fly for the airline on this plane https://youtube.com/c/CaptainBoeing

**Comment by THEONEANDONLYPLANE** [comment]
Closing this pull request. @mSparks43 please integrate this into V2, when you get to it.

**Pull request closed without merging**
