### PR TITLE
Fix #258

### LINKED ISSUE #258: Autobrakes switch should go to disarm when set to 1-MAX on ground
When the Autobrakes switch is set to 1, 2, 3, 4 or MAX on the ground the switch should automatically go to disarm. There is about a 1 second delay between selecting it to 1-MAX to Disarm as the system needs a second to recognize that the switch wants to arm one of the modes. I couldn't find this in the FCOM but this is how the system works

### PR DESCRIPTION
**Pull request by crazytimtimtim**
Fix #258

Sorry there are so many commits and some indentation/whitespace changes.

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
@mSparks43 I'm not sure I need all those parameters to be met, what do you think?

**Comment by mSparks43** [comment]
this just needs to check it was changed on the ground, and that the timer isn't already scheduled.

**Comment by crazytimtimtim** [comment]
> this just needs to check it was changed on the ground, and that the timer isn't already scheduled.

Do you mean the ET or Chrono? And what if someone has it running on the ground?

**Comment by mSparks43** [comment]
> > this just needs to check it was changed on the ground, and that the timer isn't already scheduled.
> 
> Do you mean the ET or Chrono? And what if someone has it running on the ground?

I mean the actual timer, before the call to 
```run_after_time(B747autobrake_resetOnGround, 1.0)```
you need to check if its already scheduled with 

```
if is_timer_scheduled(B747autobrake_resetOnGround) == false then
            run_after_time(B747autobrake_resetOnGround,1.0)
end
```

**Comment by crazytimtimtim** [comment]
ok. I'll add that in and mark it ready for review. Unfortunately, I can't really test now.

**Comment by crazytimtimtim** [comment]
Actually there might be a problem with 
`and simDR_engine_throttle_jet_all < 0.3 -- reversers aren't deployed, indicating a landing`
Does setting reversers cause that DR to become negative?

**Comment by mSparks43** [comment]
> and how do you get that syntax highlighting in your reply?

same as discord, three ` followed by LUA and a newline

**Comment by mSparks43** [comment]
An earlier version of this had
```Lua
simDR_ind_airspeed_kts_pilot <= 30
```
Are there any side effects to going into disarm on touchdown, and has it been flight tested?

**Comment by crazytimtimtim** [comment]
This has been fixed. Untested.


I'm sorry I haven't been able to test, I will once I get my computer running again.

**Comment by mSparks43** [comment]
yeah got it. ill pull when i can test

**Comment by crazytimtimtim** [comment]
Ok. 

Now that I think about it, I guess I could've used `math.abs` for the thrust dataref...

**Pull request merged**
