### PR TITLE
Remove outdated files/Clean up main directory/Sam Wise NML's

### PR DESCRIPTION
**Pull request by THEONEANDONLYPLANE**

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
@THEONEANDONLYPLANE do you think you can copy the improved exterior cockpit window texture from the fscabral liveries and put it in the aircraft objects folder so we see it in all liveries in this pull request?

**Comment by THEONEANDONLYPLANE** [comment]
I can't do it without direct permission, or at least it's courteous to do so.

**Comment by crazytimtimtim** [comment]
Ok.

**Comment by mSparks43** [comment]
why does this delete the nml from the yoke? it should be reflective shouldnt it?

**Comment by crazytimtimtim** [comment]
> why does this delete the nml from the yoke? it should be reflective shouldnt it?

well yeah, it should but right now it is WAY too reflective. Maybe it would be better to modify rather than completely deleting it... BUt it's not supposed to look like it has a layer of glass on it.

**Pull request closed without merging**
