### PR TITLE
Update VNAV Pages - CLB, CRZ, DES, LRC

### PR DESCRIPTION
**Pull request by gHashFlyer**
Updated vnav climb, cruise, and descent pages to display information such as ETA, fuel at destination, optimum and maximum altitudes.

Added/Revised LRC page with access via R6 from the ACT ECON CRZ page.

### CODE REVIEW

**Comment by gHashFlyer** [comment]
screenshot323

**Comment by gHashFlyer** [comment]
Resolved conflicts starting about line 302

**Comment by mSparks43** [comment]
I can merge and clean this up during the week, looks great, but it likely doesn't need those datarefs finding again, and it looks like there is a dofile in the middle of a function, json functionality should already be available to all fmc pages from the root lua document.

**Comment by gHashFlyer** [comment]
No worries - I will clean it up and verify if datarefs are needed this
week. You just keep your mind on that autopilot :)

**Comment by oMrSmith** [comment]
@gHashFlyer 
this looks great!
Say would you be up
to fix the DIST of the DEST
on the PROG page?

It is including the whole missed approach
in its calculation...

**Comment by gHashFlyer** [comment]
Cleaned up datarefs, and am working on Descent page.  Hope to push an update soon

**Comment by gHashFlyer** [comment]
Added descent page. Still needs more work, but this is a good start.

**Pull request merged**
