### PR TITLE
FMOD and TEXTURE updates

### PR DESCRIPTION
**Pull request by Matt726-S**
DO NOT MERGE UNTIL @crazytimtimtim WAKES THE HELL UP AND MERGES HIS STUFF OR IF SOMEONE MERGES THE NECESSARY CODE WITHOUT HIM

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
Sorry sorry. Did the minimums thing work?

**Comment by Matt726-S** [comment]
> Sorry sorry. Did the minimums thing work?
> […](#)

idk try it for yourself, also some bugs that aren’t fmod related:
v1 callout doesn’t work
approaching minimums sounds during takeoff for some reason (i think this is because i didnt touch the minimums dial and its set to ground level or something, make it so it doesn’t sound during takeoff)

**Comment by crazytimtimtim** [comment]
> > Sorry sorry. Did the minimums thing work?
> 
> idk try it for yourself, also some bugs that aren’t fmod related:
> v1 callout doesn’t work
> approaching minimums sounds during takeoff for some reason (i think this is because i didnt touch the minimums dial and its set to ground level or something, make it so it doesn’t sound during takeoff)

V1 has been commented out because it was the cause of blank displays. I'll add it later. I'll fix approaching minimums.

**Comment by crazytimtimtim** [comment]
And did you need me to create a display type dataref?

**Comment by Matt726-S** [comment]
> And did you need me to create a display type dataref? It already exists.

no, the sound changes in this pull request

**Comment by mSparks43** [comment]
There's a few issues in this.
firstly bus_volts 28 will be really unreliable, because the bus volts varies with load
secondly, it looks like it reverted heading_degrees, but this will fire like crazy in app.

**Comment by Matt726-S** [comment]
> There's a few issues in this.
> firstly bus_volts 28 will be really unreliable, because the bus volts varies with load
> secondly, it looks like it reverted heading_degrees, but this will fire like crazy in app.

then what should i do, i don’t see problems. also, you should fix the stupid ‘avionics power on’ or whatever so that it== 1 when ac power is connected

**Pull request merged**
