### PR TITLE
Cost Index

### PR DESCRIPTION
**Pull request by gHashFlyer**
Added a working cost index to support ECON cruise speeds. Dynamic adjustment of VNAV cruise airspeed based on cost index (CI) from the perf page.  Cost index airspeed is maximum range cruise (CI=0) to maximum mach airspeed (CI=9999). Accurately increases or decreases airspeed with headwind or tailwind, respectively. If no cost index is set, then default to M0.85. To obtain long range cruise (LRC) set cost index to 230.

### CODE REVIEW

**Comment by mSparks43** [comment]
does this override the ability to manually set cruise speed?

**Comment by gHashFlyer** [comment]
It does **not** override the ability to manually set cruise speed.

**Comment by gHashFlyer** [comment]
If the user enters a cost index, then it will fly econ cruise speed.  If the user enters no cost index, then it will fly the (default) cruise speed on the vnav crz page of the fmc.  If the default speed is nil then it will fly at mach 0.85

**Comment by mSparks43** [comment]
This is going to be merged with the AP updates once they are in a better state

**Pull request merged**
