### PR TITLE
Update Sounds options, Engine Type DR, and Callout DRs

### PR DESCRIPTION
**Pull request by crazytimtimtim**

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
Incomplete. Please don't merge either this or @Matt726-S pull request yet, or the engine sounds will break.

**Comment by crazytimtimtim** [comment]
NONONONO

**Comment by crazytimtimtim** [comment]
You broke the engine sounds

**Comment by crazytimtimtim** [comment]
@mSparks43 I'll try to quickly make the pull request.

**Comment by Matt726-S** [comment]
> You broke the engine sounds

that’s your fault

**Comment by crazytimtimtim** [comment]
> > You broke the engine sounds
> 
> that’s your fault

ik...well I _did_ say not to merge it yet.

**Comment by Matt726-S** [comment]
be more specific, what does “broke” mean to you

**Comment by crazytimtimtim** [comment]
I mean no engine sounds at all. I don't think I even created the dataref in this pull request, so fmod will check to see what it equals but it won't find the dataref, so it won't play. If I _did_ create the DRs here, it'd just be stuck on PW sounds.

**Pull request merged**
