### PR TITLE
Initial EEC functionality (GE only)

### PR DESCRIPTION
**Pull request by Marauder2882**
This is the initial version of EEC functionality, targeted at GE engines (PW & RR to follow later).

Features include:
- Takeoff calcs for N1 (Max Thrust)
- Derates for TO1/TO2 & CLB1/CLB2 (Assumed Temp to be added later)
- Manages target / max N1 during CLB
- Sets max available engine thrust based on GE engine model (B1F, B5F, etc.)
- Upper EICAS enhancements for specific GE display

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
Nice!

**Comment by crazytimtimtim** [comment]
Erm... Did you mean to make those huge changes to the SND files?

**Comment by Marauder2882** [comment]
> Erm... Did you mean to make those huge changes to the SND files and door page?
> 
> Also, I don't think you need to decode all the simconfig stuff. We create a dataref for the engine type already.
> 
> Also, I think my pull request should be merged first, as we both have acf changes, but mine are much smaller, so I can just create another pr with them. If I understand Github correctly, your changes would just be overwritten if he merges mine afterwards? :)

actually, i didn't do anything with the sound files.  something went wrong when the pull request was submitted since those files aren't in my request.

**Comment by Matt726-S** [comment]
> > Erm... Did you mean to make those huge changes to the SND files and door page?
> > Also, I don't think you need to decode all the simconfig stuff. We create a dataref for the engine type already.
> > Also, I think my pull request should be merged first, as we both have acf changes, but mine are much smaller, so I can just create another pr with them. If I understand Github correctly, your changes would just be overwritten if he merges mine afterwards? :)
> 
> actually, i didn't do anything with the sound files. something went wrong when the pull request was submitted since those files aren't in my request.

update ur fork to the latest version. fmod had changes and acf prob had changes

**Comment by crazytimtimtim** [comment]
Yeah, the branch is behind upstream. There are conflicts, so you can't just click "merge upstream," you should probably create an entirely new branch and just re-upload your changes.

**Comment by Matt726-S** [comment]
@Marauder2882 can you also make a new texture file for the thrust green thrust ref or other things like that so i can add a new font tomorrow

**Comment by Marauder2882** [comment]
> @Marauder2882 can you also make a new texture file for the thrust green thrust ref or other things like that so i can add a new font tomorrow

i'll work on that after i successfully get this commit through.

**Pull request closed without merging**
