### PR TITLE
Fix "X-Plane" Capitalization in Readme, Possible fix to Approaching Minimums Callout on Takeoff.

### PR DESCRIPTION
**Pull request by crazytimtimtim**
Heh - it was triggering me lol.

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
@mSparks43  Do you have a better idea to fix Approaching Minimums?

**Comment by mSparks43** [comment]
require flaps 25/30

**Comment by crazytimtimtim** [comment]
Thanks! Never thought of that.

**Comment by mSparks43** [comment]
image
So it should just/only be inhibited if TOGA is armed or active, landing configuration isn't required

**Comment by crazytimtimtim** [comment]
ok. So there's a toga Dataref? When does it disable?

**Comment by mSparks43** [comment]
Two xplane's internal is (used for the FD bars)
sim/cockpit2/autopilot/TOGA_status
>0 means armed/active

and 
laminar/B747/engines/TOGA_mode
set to one when you press the TOGA button. both cleared at most by 1500 feet radar altitude in the current build.

**Comment by crazytimtimtim** [comment]
Do you think the DH could ever be greater than 1500? And which do you think I should use?

**Comment by mSparks43** [comment]
should just be able to add a condition in the sound trigger that sim/cockpit2/autopilot/TOGA_status and laminar/B747/engines/TOGA_mode are both zero

**Comment by crazytimtimtim** [comment]
3merged? I could have added the TOGA thing so we don't need to wait for Matt.

**Pull request merged**
